import { WorksheetData, CellData, PrintOptions } from '../types';
import { Row } from './row';
import { Column } from './column';
export declare class Worksheet {
    private name;
    private rows;
    private columns;
    private mergedCells;
    private freezePane?;
    private printOptions?;
    constructor(name: string);
    getName(): string;
    setName(name: string): this;
    addRow(row: Row): this;
    createRow(index?: number): Row;
    getRow(index: number): Row | undefined;
    getRows(): Row[];
    removeRow(index: number): boolean;
    addColumn(column: Column): this;
    createColumn(width?: number): Column;
    getColumn(index: number): Column | undefined;
    getColumns(): Column[];
    setCell(row: number, col: number, value: any, style?: any): this;
    getCell(row: number, col: number): CellData | undefined;
    mergeCells(startRow: number, startCol: number, endRow: number, endCol: number): this;
    setFreezePane(row?: number, col?: number): this;
    setPrintOptions(options: PrintOptions): this;
    setOutlineLevel(row: number, level: number, collapsed?: boolean): this;
    setColumnOutlineLevel(col: number, level: number, collapsed?: boolean): this;
    toData(): WorksheetData;
    static fromData(data: WorksheetData): Worksheet;
}
